name: Push to Release

on:
  push:
    branches:
      - main

jobs:
  push-to-release:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up PowerShell
      uses: actions/setup-powershell@v2
      with:
        pwsh-version: '7.x'

    - name: Execute PowerShell Script
      shell: pwsh
      run: ./.github/scripts/push-to-release.ps1
      env:
        GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
