name: Push to Release

on:
  push:
    branches:
      - main

jobs:
  push-to-release:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Execute PowerShell Script
      working-directory: ./.github/scripts/
      run: pwsh -File push-to-release.ps1
      env:
        GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
